### ISSUE TITLE
Реализация метода add класса CreditAccount неверна

### ISSUE THREAD

**Issue by dryworts** [dryworts/diplomQA67Second#1]
# Описание
При пополнении счёта (метод add) переменной balace присваивается значение параметра amount, а должно быть
 баланс + пополнение
# Локация дефекта
https://github.com/dryworts/diplomQA67Second/blob/3cfac975e859db256640e9d384457c39a6d1af23/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65-L71
# Шаги воспроизведения
1. Открыть [код программы](src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Создать объект класса CreditAccount cо следующими параметрами:
3. Вставить значение переменной initialBalance = 100
4. Вставить значение переменной creditLimit = 5_000
5. Вставить значение переменной rate = 15
6. Вызвать метод add и передать в параметр 1_000
7. Запустить программу
8. Посмотреть на вывод консоли

Ожидаемый результат: баланс счёта после пополнения 1100 рублей
Фактический результат: баланс счёта после пополнения 1_000 рублей
#Тест:
https://github.com/dryworts/diplomQA67Second/blob/6e282d3797b2a1f705970fc8d20ad242d92f3114/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L24
#Скриншот

![issue1_2](https://github.com/dryworts/diplomQA67Second/assets/19948831/0fa5da5f-7f31-4c60-b608-87a523000b03)

# Окружение
* **Операционная система:** Windows 7 x64 
* **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition) 
* **Java:** OpenJDK 11

**Comment by ghost** [comment]
Исправлено add
