### ISSUE TITLE
Пополнение баланса не суммируется с текущей суммой

### ISSUE THREAD

**Issue by ghost** [dryworts/diplomQA67Second#2]
# Описание
При пополнении баланса , итоговый баланс становится суммой пополнения, а не сумма + баланс
# Локация дефекта
https://github.com/dryworts/diplomQA67Second/blob/cfffe4090ac80779d09fa39cb943f34cd78a503f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L76
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/dryworts/diplomQA67Second/blob/cfffe4090ac80779d09fa39cb943f34cd78a503f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L70-L81) в IDEA
1. Запустить тест на пополнение баланса

*Ожидаемый результат:*  Пополнение суммируется с текущим балансом
*Фактический результат:*  Итоговым балансом становится сумма пополнения
# Скриншот
![image](https://github.com/dryworts/diplomQA67Second/assets/136864184/3bcf5335-0e78-4041-b6d7-dc23d090b868)

# Окружение
* **Операционная система:**  Windows 11
* **IDE;**  IntelliJ IDEA Community Edition 2023.2.1
* **Java**  OpenJDK 11

**Comment by dryworts** [comment]
Исправлено, balance+=amount
