### ISSUE TITLE
Не корректное условие проверки баланса в методе Pay

### ISSUE THREAD

**Issue by ghost** [dryworts/diplomQA67Second#3]
# Описание
Не верное условие для данного метода
# Локация дефекта
https://github.com/dryworts/diplomQA67Second/blob/cfffe4090ac80779d09fa39cb943f34cd78a503f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L51
# Шаги воспроизведения
1. Открыть [код программы]https://github.com/dryworts/diplomQA67Second/blob/cfffe4090ac80779d09fa39cb943f34cd78a503f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L45-L55 в IDEA

*Ожидаемый результат:* Баланс должен быть больше или равен минимальному.
*Фактический результат:* Баланс может быть только больше минимального.

# Скриншот
![Screenshot_3](https://github.com/dryworts/diplomQA67Second/assets/136864184/3ad16d44-2cce-4e7f-b30d-2ad2ec702b42)
# Окружение
* **Операционная система:**  Windows 11
* **IDE;**  IntelliJ IDEA Community Edition 2023.2.1
* **Java**  OpenJDK 11

**Comment by dryworts** [comment]
Исправлено.
