### ISSUE TITLE
Не корректное условие проверки баланса в методе Add

### ISSUE THREAD

**Issue by ghost** [dryworts/diplomQA67Second#4]
# Описание
Не верное условие для данного метода
# Локация дефекта
https://github.com/dryworts/diplomQA67Second/blob/cfffe4090ac80779d09fa39cb943f34cd78a503f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L75
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/dryworts/diplomQA67Second/blob/cfffe4090ac80779d09fa39cb943f34cd78a503f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L70-L79) в IDEA

*Ожидаемый результат:* Баланс должен быть меньше или равен максимальному.
*Фактический результат:* Баланс может быть только меньше максимального.

# Скриншот

![Screenshot_4](https://github.com/dryworts/diplomQA67Second/assets/136864184/66d1a1f6-41b0-421a-96ad-b96022218116)
# Окружение
* **Операционная система:**  Windows 11
* **IDE;**  IntelliJ IDEA Community Edition 2023.2.1
* **Java**  OpenJDK 11

**Comment by dryworts** [comment]
исправлена строка 75 на  if (balance + amount <= maxBalance) {
