### ISSUE TITLE
При списании суммы больше чем текущий баланс, итоговая сумма остается положительной

### ISSUE THREAD

**Issue by ghost** [dryworts/diplomQA67Second#5]
# Описание
При списании суммы больше чем текущий баланс, итоговая сумма остается положительной. Не уменьшается
# Локация дефекта
https://github.com/dryworts/diplomQA67Second/blob/cfffe4090ac80779d09fa39cb943f34cd78a503f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L57-L59
# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/dryworts/diplomQA67Second/blob/cfffe4090ac80779d09fa39cb943f34cd78a503f/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L54-L60) в IDEA
1. Запустить тест списание суммы с баланса

*Ожидаемый результат:*  После списания 5_000 должно остаться -3_000
*Фактический результат:*  Итоговая сумма 3_000
# Скриншот
![Screenshot_5](https://github.com/dryworts/diplomQA67Second/assets/136864184/347f98ea-09c8-4720-aafb-2ae03696447c)
# Окружение
* **Операционная система:**  Windows 11
* **IDE;**  IntelliJ IDEA Community Edition 2023.2.1
* **Java**  OpenJDK 11

**Comment by dryworts** [comment]
Если же операция может привести к некорректному
     * состоянию счёта (например, баланс может уйти в минус), то операция должна
     * завершиться **вернув false и ничего не поменяв на счёте.**
