### ISSUE TITLE
Метод pay класса CreditAccount реализован с ошибками логики

### ISSUE THREAD

**Issue by dryworts** [dryworts/diplomQA67Second#6]
# Описание
Ветка if описывающая случай если операция пополнения может привести к некорректному состоянию счета реализована ошибочно.
# Локация дефекта
https://github.com/dryworts/diplomQA67Second/blob/07b460371795fb2b529e96e8c2323cb830d7982c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40-L51
# Шаги воспроизведения
1. Открыть [код программы](src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Создать объект класса CreditAccount cо следующими параметрами:
3. Вставить значение переменной initialBalance = 0
4. Вставить значение переменной creditLimit = 5_000
5. Вставить значение переменной rate = 15
6. Вызвать метод pay и передать в параметр 5_000
7. Запустить программу
8. Посмотреть на вывод консоли

Ожидаемый результат: метод должен вернуть true
Фактический результат: возвращает false
#Тест:
https://github.com/dryworts/diplomQA67Second/blob/07b460371795fb2b529e96e8c2323cb830d7982c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L229C1-L229C1
#Скриншот
![issue2](https://github.com/dryworts/diplomQA67Second/assets/19948831/bff5391f-f832-427f-a479-23702724ca41)

# Окружение
* **Операционная система:** Windows 7 x64 
* **IDE:** IntelliJ IDEA 2023.1.4 (Community Edition) 
* **Java:** OpenJDK 11

**Comment by ghost** [comment]
Исправлено pay
